export const websitesData = {
    coding: [
        { link: "https://github.com/", name: "Github" },
        { link: "https://www.codewars.com/", name: "CodeWars" },
        { link: "https://frontendmasters.com/", name: "Frontend Masters" },
        { link: "https://codepen.io/", name: "CodePen" },
        { link: "https://replit.com/", name: "Replit" },
        { link: "https://developer.mozilla.org/en-US/", name: "MDN" },
        { link: "https://www.freecodecamp.org/", name: "FreeCodeCamp" },
        { link: "https://www.hackerrank.com/", name: "HackerRank" },
        { link: "https://www.codecademy.com/", name: "CodeAcademy" },
        { link: "https://devdocs.io/", name: "Devdocs" },
        { link: "https://www.vanillajavascriptprojects.com/", name: "Vanila JS Projects" },
        { link: "https://html.com/", name: "HTML.com" },
        { link: "https://edabit.com/", name: "Edabit" },
        { link: "https://javascript30.com/", name: "JavaScript 30" },
        { link: "https://tutgator.com/tutorials/it-software/", name: "Tutgator" },
        { link: "https://johnsmilga.com/", name: "John Smilga" },
        { link: "https://www.codewars.com/", name: "CodeWars" },
        { link: "https://www.codecademy.com/", name: "CodeAcademy" },
        { link: "https://codedamn.com/dashboard", name: "codedamn" },
        { link: "https://www.javascripttutorial.net/", name: "JavaScript Tutorial" },
        { link: "https://www.30dayscoding.com/", name: "30 Days Coding" },
        { link: "https://curiousdevelopers.in/", name: "Curious Developers" },
        { link: "https://zerotomastery.io/", name: "Zero to Mastery" },
        { link: "https://www.codementor.io/", name: "CodeMentor" },
        { link: "https://dailylogochallenge.com/", name: "Daily Logo Challenge" },
        { link: "https://threejs.org/", name: "Three.js" },
        { link: "https://javascript30.com/", name: "JavaScript 30" },
        { link: "https://hacksnation.com/", name: "hacksnation" },
        { link: "https://vitejs.dev/", name: "vite" },
        { link: "https://scrimba.com/bootcamp", name: "scrimba" },
        { link: "https://app.netlify.com/teams/devharsh007/overview", name: "app.netlify" },
        { link: "https://codesandbox.io", name: "codesandbox" },
        { link: "https://stackblitz.com", name: "stackblitz" },
        { link: "https://eloquentjavascript.net/", name: "eloquentjavascript" },
        { link: "https://dev.to/", name: "Dev.to" },
        { link: "https://www.100jsprojects.com/", name: "100jsprojects" },
    ],
    AI: [
        { link: "https://claude.ai", name: "Cloude AI" },
        { link: "https://www.bing.com/search?q=cricket+live+scores&form=CPWA", name: "Bing" },
        { link: "https://chat.openai.com/", name: "Chat GPT" },
        { link: "https://www.useblackbox.io/chat", name: "BlackBox AI" },
    ],
    browse: [
        { link: "https://pomofocus.io/", name: "PomoFocus" },
        { link: "https://in.indeed.com/", name: "Indeed" },
    ],
    movies: [
        { link: "https://fmoviesto.tv/", name: "Fmovies" },
        { link: "https://www9.123moviesto.to/", name: "123Movies" },
        { link: "https://cataz.net/", name: "Cataz" },
        { link: "https://www2.solarmovie.cr", name: "SolarMovie" },
        { link: "https://www.putlockers.do", name: "Putlockers" },
        { link: "https://animesuge.to/home", name: "animesuge.to" },
        { link: "https://aniwatch.to/", name: "aniwatch.to" },
        { link: "https://mangaplus.shueisha.co.jp/updates", name: "mangaplus.shueisha" },
    ],
    torrent: [
        { link: "https://www.limetorrents.lol/", name: "LimeTorrents" },
        { link: "https://rarbgaccessed.org/", name: "RARBG" },
        { link: "https://eztv.re/", name: "EZTV" },
        { link: "https://yts.monster/", name: "YTS" },
        { link: "https://www.torlock.com/", name: "TorLock" },
        { link: "https://gtdb.cc/", name: "GTDB" },
        { link: "https://katcr.to/", name: "KATCR" },
        { link: "https://torrentz2.nz/", name: "Torrentz2" },
        { link: "https://thepiratebay.org/index.html", name: "The Pirate Bay" },
        { link: "https://1337x.to", name: "1337x" },
    ],
    games: [
        { link: "https://fitgirl-repacks.site/", name: "FitGirl Repacks" },
        { link: "https://repack-mechanics.com/", name: "Repack Mechanics" },
        { link: "https://www.shanaproject.com/", name: "ShanaProject" },
    ],
    study: [
        { link: "https://www.kingauthor.net/", name: "KingAuthor" },
        { link: "https://archive.org/", name: "Archive.org" },
        { link: "https://instapdf.in/", name: "InstaPDF" },
        { link: "https://www.pdfnotes.co/", name: "PDFNotes" },
        { link: "https://givegita.com/", name: "GiveGita" },
        { link: "https://it-ebooks.info", name: "IT-Ebooks" },
        { link: "https://www.pdfdrive.com/", name: "PDFDrive" },
        { link: "https://manybooks.net/", name: "ManyBooks" },
        { link: "https://www.globalgreyebooks.com/index.html", name: "Global Grey Ebooks" },
        { link: "https://epuborigin.com/", name: "Epub Origin" },
        { link: "https://pll.harvard.edu/", name: "harvard.edu" },
    ],
    softwares: [
        { link: "https://crackingpatching.com", name: "CrackingPatching" },
        { link: "https://www.photopea.com/", name: "Photopea" },
        { link: "https://ask4pc.net/", name: "Ask4pc" },
        { link: "https://piratepc.me/", name: "PiratePC" },
        { link: "https://up4pc.com/", name: "Up4PC" },
        { link: "https://getintopc.com/", name: "GetIntoPC" },
    ],
    design: [
        { link: "https://customstart.page/", name: "CustomStart" },
        { link: "https://fontawesome.com/", name: "FontAwesome" },
        { link: "https://coolors.co/", name: "Coolors" },
        { link: "https://icons.getbootstrap.com/", name: "Bootstrap Icons" },
        { link: "https://pixabay.com/", name: "Pixabay" },
        { link: "https://www.svgrepo.com/", name: "SVGRepo" },
        { link: "https://www.flaticon.com/", name: "Flaticon" },
        { link: "https://css-tricks.com/", name: "CSS-Tricks" },
        { link: "https://iconify.design/", name: "Iconify.design" },
    ],
    tools: [
        { link: "https://www.ilovepdf.com/", name: "ILovePDF" },
        { link: "https://tinywow.com/", name: "TinyWow" },
        { link: "https://onlinetools.com/", name: "OnlineTools" },
    ],
};

